version: '3.7'

# /opt/kafka/bin/kafka-console-producer.sh --bootstrap-server 127.0.0.1:9092 --topic test-topic < /data.txt

services:

  kafka:
    image: wurstmeister/kafka:2.12-2.5.0
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: kafka
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_CREATE_TOPICS: "test-topic:2:1"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./producer-data.txt:/producer-data.txt
    depends_on:
      - zookeeper

  # required by kafka image
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "127.0.0.1:2181:2181"



